spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: aryan@123
  # If you use Flyway, let it reuse the same creds (otherwise delete this block
  # or set flyway.enabled=false until you have migrations):
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  logging:
    level:
      org.springframework.boot.context.config: DEBUG
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242